name: battery_info_app
description: Battery info app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # battery_plus: ^1.1.0
  glassmorphism_ui: ^0.2.0
  battery_info: ^1.0.8

  # cupertino_icons: ^1.0.2

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/

  # fonts:
  #   - family: Hero
  #     fonts:
  #       - asset: assets/fonts/Hero-Regular.ttf
  #       - asset: assets/fonts/Hero-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/Hero-Bold.ttf
  #         weight: 700
